name: appointmentpractice
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.9
  cupertino_icons: ^1.0.8
  intl: ^0.18.0  # Updated to match Flutter 3.x
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  pdf: ^3.10.8
  path_provider: ^2.1.2
  share_plus: ^7.2.2
  printing: ^5.11.1
  google_fonts: ^6.1.0  # Added for PDF fonts

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/umplogo.png